- maat-orchestration/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-912)
Setup Sonar.
> LCAM-912|Setup Sonar

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-962)
Updated the CODEOWNERS file and PR template.
> LCAM-962|Update codeowners and PR template

- .github/dependabot.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-962)
Update the dependaot yaml.
> LCAM-962|Update the dependaot yaml

- maat-orchestration/src/main/java/uk/gov/justice/laa/maat/orchestration/mapper/HardshipReviewMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/maat/orchestration/util/CurrencyUtil.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/maat/orchestration/util/CurrencyUtilTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-625)
> LCAM-625|Integrate Find hardship with MAAT

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/maat/orchestration/dto/GenericDTO.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-625)
> LCAM-625|Update DTO fields and crime-commons version

- maat-orchestration/src/main/resources/logback.xml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1102)
> Add logback file for distributed tracing

- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/Constants.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/ProceedingsMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1106)
> WIP: LCAM 1106 Add Unit Tests for Proceedings Mapper

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/ApplicationDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipApiServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-909)
Orchestrate Update Hardship flow.
> LCAM-909|Orchestrate Update Hardship flow

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/Constants.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1044)
Added unit tests for CMA Orchestration service.
> Add unit tests for CMA Orchestration service

- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/controller/HardshipControllerTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/controller/MeansAssessmentControllerTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/Constants.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipReviewMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/ProceedingsMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/AssessmentSummaryServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ContributionServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipApiServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentApiServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1106)
Work on the unit tests for the proceedings mapper was accidentally merged in when merging other unit tests, there was some review comments that needed to be addressed and one of the unit test scenarios was only half written. This pull request address these things.
> LCAM 1106 Finish proceedings mapper unit tests

- maat-orchestration/Dockerfile
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/controller/MeansAssessmentController.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ContributionApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/util/DateUtil.java
- maat-orchestration/src/main/resources/application.yaml
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/config/MockServicesConfiguration.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/controller/MeansAssessmentControllerTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/Constants.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MeansAssessmentServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/util/DateUtilTest.java
- maat-orchestration/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1044)
Orchestrate CMA Find flow.
> Orchestrate CMA Find flow

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipApiServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipServiceTest.java
> LCAM-1098-Rollback Hardship

- maat-orchestration/Dockerfile
- maat-orchestration/src/main/resources/application.yaml
- maat-orchestration/src/test/resources/application.yaml
> Fixed the CMA find url

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/HardshipApiService.java
- maat-orchestration/src/main/resources/application.yaml
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/api/HardshipApiServiceTest.java
- maat-orchestration/src/test/resources/application.yaml
[LCAM-1193](https://dsdmoj.atlassian.net/browse/LCAM-1193)
Rollback hardship review.
[LCAM-1193]: https://dsdmoj.atlassian.net/browse/LCAM-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LCAM-1193|Rollback hardship review

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/config/ServicesConfiguration.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/RepOrderDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/SendToCCLFDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
- maat-orchestration/src/main/resources/application.yaml
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/config/MockServicesConfiguration.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiServiceTest.java
- maat-orchestration/src/test/resources/application.yaml
> Update Send to CCLF

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1243)
Update rollback handling logic for Hardship flows.
> LCAM-1243|Update rollback handling logic for Hardship flows

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1197)
Update Hardship flow to populate the latest assessment summary data on the Application DTO.
> LCAM-1197|Update Hardship flow

- maat-orchestration/src/main/resources/schemas/crown-court/common/apiHardshipOverview.json
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1254)
See [main PR](https://github.com/ministryofjustice/laa-crown-court-proceeding/pull/146) for CCP for details.
> LCAM 1254 Realigned Hardship Overview Schema Following Changes in CCP

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1266)
> Fix the NPE in handling solicitor costs mapping

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/ProceedingsMapper.java
- maat-orchestration/src/main/resources/schemas/crown-court/apiProcessRepOrderRequest.json
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/ProceedingsMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1256)
> LCAM 1256 Remove laaTransactionId from Schemas

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/jackson/SysGenDateDeserializer.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/jackson/SysGenDateDeserializerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1271)
> LCAM-1271-adding null check

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/config/ServicesConfiguration.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/AssessmentSummaryService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/MaatCourtDataService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/config/MockServicesConfiguration.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/MeansAssessmentIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/AssessmentSummaryServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MaatCourtDataServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/utils/WiremockStubs.java
- maat-orchestration/src/test/resources/application.yaml
> Get Assessment Summary

- README.md
- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/ApplicantDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/FinancialAssessmentDTO.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1281)
Fixed deserialisation issues and updated README.
> Fix deserialisation issues

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1286)
> Fix the validation around handling user session

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/HardshipService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipReviewMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/HardshipServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1288)
Fixed the mapping issues in the hardship flow.
Tidied up the TestModelDataBuilder.java.
> LCAM-1288|Fix the hardship mapping issues

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/controller/MeansAssessmentController.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/exception/MaatOrchestrationException.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/MeansAssessmentIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1268)
Changes to return custom HTTP status code on rollback
Related MAAT Application PR
https://github.com/ministryofjustice/laa-maat-application/pull/519/files
> Changes to return custom HTTP status code on rollback

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/controller/HardshipController.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1302)
> LCAM-1302|Fix the rollback logic for hardship flows

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/AssessmentSummaryService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/AssessmentSummaryServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1311)
Use the assessment status to determine the current assessment type.
Fix the status description.
> LCAM-1311|Fix the assessment summary display

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/MaatCourtDataService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1317)
Removed the logging of ApplicationDTO to avoid logging sensitive info.
Logging the details stored procedure request in the executeStoredProcedure method.
> LCAM-1317|Logging changes

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/IncomeEvidenceSummaryDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/JobSeekerDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/PassportedDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1326)
Reset the passported DTO after creating a new means assessment.
> LCAM-1326|Reset the passported DTO after creating a new means assessment

- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1326)
Added Unit test to cover the passport dto clearing after means assessment.
> Unit test to cover the passport dto clearing

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/exception/CrimeValidationExceptionHandler.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1322)
Allow validation error messages to be returned to MAAT.
Add exception handling for ValidationException class.
> LCAM-1322|Enhance error message handling

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
Log the error message before rolling back the transaction
> Log the error message before rolling back the transaction

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/RoleDataItemDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/validation/UserSummaryDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
> Moved Reservations Entity to DTO

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1372)
Log the exception before throwing MAATOrchestrationException.
> LCAM-1372|Enhance error logging

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1374)
> LCAM-1374-capture exception

- maat-orchestration/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1368)
> LCAM-1368|Update mod schemas version

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/CCLFUpdateService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/CCLFUpdateServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
> Clean up CCLF Update Logic

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/ContributionMapper.java
> Null Check

- .git-crypt/keys/default/0/F2471D464D4D78041FD464365CB331F148689766.gpg
New collaborators:
48689766 Karl Baker <karl.baker@digital.justice.gov.uk>
> Add 1 git-crypt collaborator

- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/MeansAssessmentIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1476)
- Fix failing integration tests.
> Fix failing integration tests

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1529)
- Updated commons classes version to pull in changes to requestSource enum: https://github.com/ministryofjustice/laa-crime-commons/pull/136
- Commented out call to application tracking service and integration test assertions. Fixing this will take place as part of a separate ticket https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881/backlog?selectedIssue=LCAM-1531 once the main hardship flow are working.
> LCAM 1529 Issue Deserialising Request Source When Calling Application Tracking Service 

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1531)
Call the ATS service only the maat associated with USN
> LCAM-1531-fix-ats-call

- .circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1538)
CircleCI integration with slack for deployment and build notifications as detailed in this tutorial https://circleci.com/docs/slack-orb-tutorial/
> LCAM-1538|Slack and CircleCI integration for deployment and build notifications

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/CATApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/ContributionApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/HardshipApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MeansAssessmentApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/ProceedingsApiService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1576)
Added the request logging before calling any API service.
Updated the logging to use uniform pattern, updated the log information to use consistent service names.
> LCAM-1576|Streamline request and response logging

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/config/ServicesConfiguration.java
- maat-orchestration/src/main/resources/application.yaml
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/config/MockServicesConfiguration.java
- maat-orchestration/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1593)
Removed the unused contribution end point and associated config.
> LCAM-1593|Clean up contribution end points

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/FeatureToggleDTO.java
> Added new field isEnabled for Feature Toggle

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1648)
Update latest version of crime common
Remove hardship progress mapping and related test cases
> LCAM-1648-remove hardship progress

- maat-orchestration/build.gradle
> Upgraded Crime Commons Classes Version

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1660)
When there is no partner on the application, the array list would be empty. Enhanced the code to fix the java.lang.ArrayIndexOutOfBoundsException in getPartnerDetails().
> Handle no partner scenario

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1728)
- Upgrade to new version for income due date is not mandatory 
- Added null check when partner income evidence is null 
> LCAM-1728-schema-changes

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/common/Constants.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1791)
Update adhoc as  PARTNER when the  income evidence is a partner otherwise update APPLICANT.
> LCAM-1791-update-evidence-adhoc

- helm_deploy/laa-maat-orchestration/values-dev.yaml
- helm_deploy/laa-maat-orchestration/values-prod.yaml
- maat-orchestration/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4092)
Updated MAAT Data API base URL to point to CP in development.
> LASB-4092|Update MAAT Data API base URL to point to CP

- helm_deploy/laa-maat-orchestration/values-dev.yaml
- helm_deploy/laa-maat-orchestration/values-prod.yaml
- helm_deploy/laa-maat-orchestration/values-test.yaml
- helm_deploy/laa-maat-orchestration/values-uat.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4077)
Added ModSecurity to both the prod and non-prod environments. 
> LASB-4077 - Add ModSecurity to both non-prod and prod
