- maat-orchestration/src/main/java/uk/gov/justice/laa/maat/orchestration/enums/HardshipReviewDetailReason.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/maat/orchestration/mapper/HardshipReviewMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/maat/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/maat/orchestration/enums/HardshipReviewDetailReasonTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/maat/orchestration/mapper/HardshipReviewMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1102)
In order to fix the Extra expenditure Reason populating the id field on the HRReasonDTO.
Add a null check around HardshipReviewDetailCode mapping.
Add missing mapping on NewWorkReasonDTO.
> LCAM-1102|Fix the missing Extra expenditure reason display

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/jackson/LocalDateTimeDeserializer.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/controller/HardshipControllerTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/controller/MeansAssessmentControllerTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/MeansAssessmentIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/jackson/LocalDateTimeDeserializerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1305)
As an interim solution, using custom deserialisers for handling the different timestamp formats.
> LCAM-1305|Use custom deserializers for the different timestamp formats

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1318)
MAAT application is expecting the enabled field to be FALSE by default on IncomeEvidenceSummaryDTO.
> LCAM-1318|Default the income evidence field to mimic MAAT application

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
- maat-orchestration/src/main/resources/logback.xml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1424)
Log the MAAT API response from stored procedure call. 
Obfuscate sensitive fields before logging the response from MAAT API.
> LCAM-1424|Obfuscate sensitive fields before logging

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
This PR updates the timestamp validation in the _ValidationSerivce_ to exclude milliseconds as part of the check on whether the application and rep order timestamps are equal. The _ValidationService_ is also slightly refactored in this process to make it clearer that if the application timestamp is null then there isn't anything further to validate with the timestamps.
This PR also adds some new test cases which specifically cover the timestamp validation logic, as this was previously only covered for failing cases, with the passing cases covered as part of the wider tests on the _validate_ method.
Note that I have worked on this PR going directly from the description in the story (below), without further inspection of the relevant stored procedure.
[Link to …
> Update timestamp validation in ValidationService

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
This PR creates a method for checking a user's permission to edit the uplift fields of a legal aid application. It makes the assumption that a user has permission to change uplift fields only if the user can edit both the uplift applied and removed fields; if only one of these roles exists or is enabled against the user, a _ValidationException_ will be thrown.
It should also be noted that this PR is not checking the existing uplift applied and/or removed dates as the story could be taken to imply; after discussion of the story, it was confirmed that the method in this PR is solely about checking permissions of a user to edit these fields.
This PR also performs some other housekeeping, re-ordering the methods within the _ValidationService_ to list them
alphabetically and grouped by method …
> Migrate Uplift Data Item Validation Logic to Orchestration Service

- helm_deploy/laa-maat-orchestration/templates/ingress.yaml
This PR fixes the ingress YAML to remove an extra `{{- end }}` statement which caused a parse error when running `helm upgrade` in the deploy pipeline.
> Fix ingress YAML

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/controller/MeansAssessmentController.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1430)
Updated error handling to ensure we rollback the transaction in case of a MAAT Server exception. Using the latest commons-client jar to allow the error message to be passed to the MAAT Application so that the validation error message is displayed on the UI.
Also, updated logging to print the financial transaction ID.
> LCAM-1430|Enhance eror handling to display the validation error on UI

- maat-orchestration/src/main/resources/logback.xml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1451)
Updated the list of sensitive fields that needs to be obfuscated before logging.
> LCAM-1451|Mask sensitive fields before logging

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipReviewMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1540)
- Null check on solicitors costs estimated total value was causing null solicitor costs data to be sent through to the hardship service, as at this point the estimated total hasn't been calculated. Instead I've altered the check to confirm both rate and hours are not null (these should both be entered for any valid solicitors costs entry).
> LCAM 1540 Solicitors Costs Not Record on Database When Creating Hardship

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/common/Constants.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1450)
When user updates the caseType on the Application tab, but there is a validation error around the committal date, the caseType in the ApplicationDTO is updated but not in the DB, causing a mismatch. This triggers a validation check check_alert_message in pre_update_checks that wipes the assessment in the stored procedure and sets an alert message to say a reassessment is required.
This change is to check for the alert messages populated in the stored procedure so that these can be displayed on the UI.
We need to add some additional front-end checks around the case type and committal date so that this scenario can be avoided.
> LCAM-1450|Handle alert messages to display appropriate error on UI

- .github/workflows/pr-checks.yml
This commit adds basic PR checks for the Orchestration Service repo, which check to make sure that there is a non-default description, that the number of commits is no greater than 40 and that a link exists to a Jira work item.
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1631)
> Add basic PR checks for Orchestration Service repo

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/enums/FeatureToggle.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/UserMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/FeatureDecisionService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/RepOrderService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ValidationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/WorkflowPreProcessorService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/FeatureDecisionServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/RepOrderServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/WorkflowPreProcessorServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationServiceTest.java
This PR updates the Hardship and Means Assessment workflows to use the _WorkflowPreProcessorService_ for validating incoming requests, specifically to ensure that the application status and timestamp are valid, as well as to ensure that the user is authorised for the action that they're attempting to perform.
This validation is only triggered from the Hardship and Means Assessment workflows when the `MaatPostAssessmentProcessing` feature flag has been enabled and additionally, in the case of Means Assessment workflows, only when the Crown Court Contribution Service has been enabled.
The _FeatureDecisionService_ has been refactored as part of this PR to consolidate common logic and the tests have been parameterised to try and ensure that duplication does not become an issue as the number …
> Run Hardship and Means Assessment validations via WorkflowPreProcessorService

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/FeatureDecisionService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/FeatureDecisionServiceTest.java
- maat-orchestration/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1654)
As part of this change the logic in FeatureDecisionService is updated to use the newly added IS_ENABLED column on the FEATURE_TOGGLE table. This allows feature toggles that apply to all users to be disabled on a user-specific basis.
> LCAM-1654|Update feature toggle to use IS_Enabled flag

- helm_deploy/laa-maat-orchestration/templates/_environment.tpl
- helm_deploy/laa-maat-orchestration/values-dev.yaml
- helm_deploy/laa-maat-orchestration/values-prod.yaml
- helm_deploy/laa-maat-orchestration/values-test.yaml
- helm_deploy/laa-maat-orchestration/values-uat.yaml
- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/config/ServicesConfiguration.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat/FinancialAssessmentDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/IncomeEvidenceService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/EvidenceApiService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiService.java
- maat-orchestration/src/main/resources/application.yaml
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/config/MockServicesConfiguration.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/Constants.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/IncomeEvidenceServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/api/EvidenceApiServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/api/MaatCourtDataApiServiceTest.java
- maat-orchestration/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1621)
- Added configuration, service method and mapper to call the evidence service to create default evidence items.
- Added configuration, service method and mapper to call maat api to update the means assessment with the details of the new evidence items.
- Added method to sequence the above calls and update the workflow request with the details of the evidence items created.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of …
> LCAM 1621 Persist Income Evidence

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/EvidenceDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/FinAssIncomeEvidenceDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/PassportAssessmentDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/dto/maat_api/PassportAssessmentEvidenceDTO.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1662)
Enhanced the getDateReceived method in the IncomeEvidenceMapper.
When determining the Evidence Received Date, we need to check if the evidence was already provided as part of a previous passported assessment or means assessment. The DATE_RECEIVED from the latest evidence record is picked and saved to the new evidence record.
> LCAM-1662|Enhance the getDateReceived method in the IncomeEvidenceMapper

- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/CCLFUpdateServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/FeatureDecisionServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ValidationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1647)
Replace all JUnit 5 assertions with AssertJ assertions in Orchestration Service codebase
> LCAM-1647-consistent-use-of-assertJ

- maat-orchestration/build.gradle
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapper.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/WorkflowPreProcessorService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/EvidenceOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/IncomeEvidenceMapperTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/WorkflowPreProcessorServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/EvidenceOrchestrationServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1688)
Enhanced the update_income_evidence flow to include the business logic related to Uplift functionality.
When Uplift fields (Uplift Applied Date, Uplift Removed Date) are modified new validation is invoked to check the user privileges.
When the uplift is changed as a result of updating the income evidence, contribution is recalculated. 
> LCAM-1688|Enhance Update Income Evidence flow to include Uplift logic

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/ContributionMapper.java
This PR adds mapping of an existing Crown Court hardship review assessment to the _ApiMaatCalculateContributionRequest_ sent to the Contributions Service for the purpose of calculating contributions.
This mapping fixes a bug where contributions were not calculated after a passing Crown Court hardship review, as to the Contributions Service there had been no overall change in assessment status, meaning that contributions were calculated to be the same as previous and therefore no new contribution was persisted.
As part of this work, it was considered to also map Magistrates Court hardship review assessments to the same request to the Contributions Service, as the mapping method changed in this commit is called from various paths, including when creating and updating means assessments, …
> Pass existing Crown Court hardship review assessment to C3

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/HardshipMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/TestModelDataBuilder.java
This PR fixes the precision of solicitors hours from 1dp to 2dp, which aligns with how solicitors log their time and how caseworkers expect to be able to input this into MAAT. Both MAAT and the Hardship Service already use a precision of 2dp for these hours, so this commit fixes the mapping between the Orchestration Service and the Hardship Service to ensure that the correct value is passed when creating the hardship review.
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1736)
> Fix precision of solicitors hours to 2dp

- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/CrownCourtIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/HardshipIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/integration/MeansAssessmentIntegrationTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/utils/WiremockStubs.java
This PR adds integration tests for the _CrownCourtController_, which calls through to update Crown Court proceedings via the Crown Court Proceedings Service.
This PR also renames the stub methods for the Crown Court Proceedings Service used to update proceedings, to make
it clearer what these methods are stubbing. This is especially true for the update method available at
`api/internal/v1/proceedings/update-crown-court` within CCP, which is not updateing the Crown Court but is actually
updating the Crown Court Outcome.
There should be a later clean-up task to update Crime Commons to rename the _ApiUpdateCrownCourtRequest_ class to be called _ApiUpdateCrownCourtOutcomeRequest_, to specify what it is actually being used for (which is **not** updating the Crown Court) and to align with the …
> Add CrownCourtController integration tests

- maat-orchestration/build.gradle
This PR fixes the [recently published security vulnerability] (https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-9486467) in `spring-security-crypto` by forcibly bumping the dependency up to version `6.4.4`.
Spring Boot version `3.4.4` does patch `spring-security-crypto` to this same version, but in order to upgrade Spring Boot, Crime Commons modules also need to be upgraded at the same time, which has more potential to cause problems elsewhere. In that context and to ensure that the Orchestration Service can be as quickly fixed to allow deployments once again, this temporary fix is made in this PR until such time as Spring Boot is upgraded to `3.4.4`.
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1788)
> Fix security vulnerability in spring-security-crypto

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ApplicationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/EvidenceOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ApplicationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/EvidenceOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/HardshipOrchestrationServiceTest.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/orchestration/MeansAssessmentOrchestrationServiceTest.java
This PR fixes inconsistencies introduced regarding Rep Order date modified timestamps and the timestamp returned as part of the `ApplicationDTO` object. Previously, the date modified field of the Rep Order was being updated but the `timestamp` field of the `ApplicationDTO` was not altered, resulting in the caller receiving the previous date modified timestamp and not the updated one.
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1739)
> Fix inconsistencies with Rep Order date modified

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/ApplicationService.java
- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/service/RepOrderService.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/data/builder/MeansAssessmentDataBuilder.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/service/ApplicationServiceTest.java
This PR updates the _RepOrderService_ to get and return the latest _RepOrderDTO_ immediately after updating the date modified on the Rep Order.
The reason for this change is because Hibernate automatically updates the date modified field of the Rep Order entity whenever there are _any_ changes to said Rep Order; this is resulting in a situation at the moment where a request to patch the Rep Order in the Court Data API with a new date modified first updates the field to the value we pass, but is then updated immediately after by Hibernate because the Rep Order entity was changed.
This is a separate issue in its own right and a [task has been captured to return the updated _RepOrderDTO_ from the Court Data API endpoint] (https://dsdmoj.atlassian.net/browse/LCAM-1806) that we are calling to …
> Use correct timestamp set in Rep Order by Hibernate in ApplicationDTO

- maat-orchestration/src/main/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapper.java
- maat-orchestration/src/test/java/uk/gov/justice/laa/crime/orchestration/mapper/MeansAssessmentMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3782)
Fixed NPE in assessment mapping. 
The cma endpoint within MAAT orchestration service is receiving WorkflowRequest to create crime means assessments. This MAAT orchestration service maps the incoming WorkflowRequest in to a ApiCreateMeansAssessmentRequest in order to call the downstream CMA service to perform the work. During the mapping some of the WorkflowRequest's values are null causing NPEs. This fixes the cause of the NPEs - passing nulls to the BigDecimal.valueOf method.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or …
> LASB-3782 - fixed NPE in assessment mapping
